name: Run Tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.pip') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.pip && pip install -r requirements.dev.pip
      - name: Run Migrations
        run: python src/manage.py migrate --settings=settings.tests --noinput
      - name: Run Tests
        run: python src/manage.py test apps --settings=settings.tests --verbosity=2 --noinput
